version: 2

models:
  - name: silver_sensor_readings
    columns:
      - name: SENSOR_ID
        tests:
          - not_null

      - name: METRIC_NAME   # <--- The test MUST be here
        tests:
          - not_null
          - accepted_values:
              values: ['TEMPERATURE', 'PRESSURE', 'VIBRATION', 'POWER CONSUMPTION']

      - name: METRIC_VALUE  # <--- METRIC_VALUE should only have not_null
        tests:
          - not_null

      - name: INGESTION_TIMESTAMP
        tests:
          - not_null
