version: 2

models:
  - name: silver_sensor_readings
    description: "Standardized and cleaned sensor data."
    columns:
      - name: SENSOR_ID
        tests:
          - not_null

      - name: METRIC_NAME
        tests:
          - not_null
          - accepted_values:
              # Updated to match the actual strings from your Python Producer
              values: [
                'TEMPERATURE (C)', 
                'PRESSURE (BAR)', 
                'VIBRATION (HZ)', 
                'POWER CONSUMPTION (KW)'
              ]

      - name: METRIC_VALUE
        tests:
          - not_null

      - name: INGESTION_TIMESTAMP
        tests:
          - not_null
