version: 2

models:
  - name: silver_sensor_readings
    columns:
      - name: SENSOR_ID
        tests:
          - not_null
      - name: METRIC_NAME
        tests:
          - not_null
          - accepted_values:
              # We will look for these core clean strings
              values: ['TEMPERATURE', 'PRESSURE', 'VIBRATION', 'POWER CONSUMPTION']
