SELECT 
    SENSOR_ID AS "SENSOR_ID",
    -- This strips (C), (BAR), etc. to leave just 'TEMPERATURE', 'PRESSURE'
    UPPER(REGEXP_REPLACE(METRIC_NAME, ' \\(.*\\)', '')) AS "METRIC_NAME",
    METRIC_VALUE AS "METRIC_VALUE",
    INGESTION_TIMESTAMP AS "INGESTION_TIMESTAMP"
FROM raw_data
