version: 2

sources:
  - name: stg_db           # This MUST match the SQL file above
    database: STG_DB
    schema: STG_SCHEMA
    tables:
      - name: STG_SENSOR_DATA
      - name: RAW_SENSOR_STREAM
      - name: SENSOR_DATA_STREAM
