import os
import glob
from minio import Minio
from minio.error import S3Error

# --- CONFIGURATION ---
MINIO_URL = "localhost:9000" 
ACCESS_KEY = "admin"
SECRET_KEY = "password123"
BUCKET_NAME = "manufacturing-landing-zone"

def reset_and_upload():
    client = Minio(
        MINIO_URL,
        access_key=ACCESS_KEY,
        secret_key=SECRET_KEY,
        secure=False
    )

    try:
        # 1. DELETE EXISTING BUCKET (Clean Slate)
        if client.bucket_exists(BUCKET_NAME):
            print(f"--- Cleaning existing bucket: {BUCKET_NAME} ---")
            objects = client.list_objects(BUCKET_NAME, recursive=True)
            for obj in objects:
                client.remove_object(BUCKET_NAME, obj.object_name)
            client.remove_bucket(BUCKET_NAME)
            print("Bucket deleted successfully.")

        # 2. CREATE NEW BUCKET
        client.make_bucket(BUCKET_NAME)
        print(f"--- Created new bucket: {BUCKET_NAME} ---")

        # 3. AUTO-FIND AND UPLOAD DATA
        # Look for the latest CSV file generated by your producer
        csv_files = glob.glob("mfg_sensor_batch_*.csv")
        
        if not csv_files:
            print("ERROR: No 'mfg_sensor_batch_*.csv' files found in the current directory!")
            print("Please run your 'manufacturing_data_producer.py' script first.")
            return

        for local_file in csv_files:
            destination_name = os.path.basename(local_file)
            client.fput_object(BUCKET_NAME, destination_name, local_file)
            print(f"✅ SUCCESS: {local_file} uploaded to MinIO as {destination_name}")

    except S3Error as err:
        print(f"MinIO Error: {err}")

if __name__ == "__main__":
    reset_and_upload()
