name: 'mfg_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'mfg_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  mfg_dbt_project:
    # 1. Bronze/Staging: Raw Ingestion (Mapped to STG_DB.STG_SCHEMA)
    bronze:
      +database: STG_DB
      +schema: STG_SCHEMA
      +materialized: view

    # 2. Silver/Reporting: Transformed Layer (Mapped to DW_DB.RPT_SCHEMA)
    silver:
      +database: DW_DB
      +schema: RPT_SCHEMA
      +materialized: table

    # 3. Gold: Final Analytics (Mapped to DW_DB.RPT_SCHEMA)
    gold:
      +database: DW_DB
      +schema: RPT_SCHEMA
      +materialized: table
