mfg_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      # Added a default string as a second argument to clear the IDE errors
      account: "{{ env_var('TF_VAR_snowflake_account', 'BKVGNQZ-UO15536') }}"
      user: "{{ env_var('TF_VAR_snowflake_user', 'ROSHAN') }}" 
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'Rosh20090798395@') }}"
      role: SYSADMIN
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'MFG_BRONZE_DB') }}" 
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'KAFKA_INGEST') }}"     
      warehouse: COMPUTE_WH
