# profiles.yml
mfg_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('TF_VAR_snowflake_account') }}"
      user: "{{ env_var('TF_VAR_snowflake_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: SYSADMIN
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}" # This will now be MFG_BRONZE_DB
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"     # This will now be KAFKA_INGEST
      warehouse: COMPUTE_WH
